### ISSUE TITLE
Ghostery blocks Google Fonts

### ISSUE THREAD

**Issue by s1e2b3i4** [ghostery/GhosterySafari#10]
Google fonts are blocked in my configuration.
I think this comes from the privacy filter.
I would like to exclude requests to `fonts.googleapis.com` from the blocking.
But it seems that the exclude-list only considers the website I visit and not other requests the website makes.

Could you please improve this behavior or guide me in the right direction on how I can achieve the desired behavior?

**Comment by chrmod** [comment]
Ghostery for Safari was recently updated and is now implemented as a WebExtension. New repository is here. Please report a new issue if there are any problems with new version. https://github.com/ghostery/ghostery-dnr-extension
