### ISSUE TITLE
Youtube Ads are not blocked

### ISSUE THREAD

**Issue by juliusbartolome** [ghostery/GhosterySafari#12]
Hello guys!

First of all I am thankful on your work to block ads! I am a user of ghostery for almost a year now and tried this on safari today. One of the first things I noticed is that it is allowing youtube ads to play when playing videos which is already blocking the normal extension. 

I hope someone can look into this issue, just let me know if I can be of any help in either development or testing. I just need a helping hand to get things started.

Thanks and more power to you guys!

**Comment by chrmod** [comment]
Ghostery for Safari was recently updated and is now implemented as a WebExtension. New repository is here. Please report a new issue if there are any problems with new version. https://github.com/ghostery/ghostery-dnr-extension

Note that blocking YT with the technology provided by the platform is not possible at the moment. If you know any content blocker that does that, please let us know so we can investigate.
