### ISSUE TITLE
Stopped to work on Safari 15.2?

### ISSUE THREAD

**Issue by shina** [ghostery/GhosterySafari#14]
It suddenly stopped to work in Safari 15.2, not sure though if the Safari's version has something to do with it.

It just not work and doesn't appear in my extensions anymore. It was working before and I just realised today that it is not working anymore.

Is it only me?

**Comment by chrmod** [comment]
Ghostery for Safari was recently updated and is now implemented as a WebExtension. New repository is here. Please report a new issue if there are any problems with new version. https://github.com/ghostery/ghostery-dnr-extension

Note that you need MacOS Monterey to use new version of Ghostery for Safari
