### ISSUE TITLE
Ghostery Rewards and Anti Tracking

### ISSUE THREAD

**Issue by ghost** [ghostery/GhosterySafari#5]
I really believe Ghostery Rewards can be a solid Honey alternative and would love to see it on Ghostery Lite. I just want to open the issue to see if integrating something like that is possible with Safari supporting WebExtensions now (see [WWDC](https://developer.apple.com/videos/play/wwdc2020/10665/))? Same with Anti Tracking?

**Comment by chrmod** [comment]
Ghostery for Safari was recently updated and is now implemented as a WebExtension. New repository is here. Please report a new issue if there are any problems with new version. https://github.com/ghostery/ghostery-dnr-extension

Answering your question:
* Ghostery Rewards project is retired. Currently there are no plans to push into this directon
* New version of Safari Extension is based on WebExtentions - enjoy
* We work actively on porting Anti-Tracking to Safari
