### ISSUE TITLE
Error Enabling Extension In Safari 14

### ISSUE THREAD

**Issue by AFabyTWE** [ghostery/GhosterySafari#6]
When attempting to enable the Ghostery Lite extension in Safari 14, I receive the following error:

Safari detected an app or service that interfered with clicking.

To protect your privacy and security, this extension was not turned on. After quitting the app or service, you can try to turn on this extension again.

If I click it again, it will enable.

**Comment by chrmod** [comment]
Ghostery for Safari was recently updated and is now implemented as a WebExtension. New repository is here. Please report a new issue if there are any problems with new version. https://github.com/ghostery/ghostery-dnr-extension
