### ISSUE TITLE
Universal Binary for Apple Silicon

### ISSUE THREAD

**Issue by amw** [ghostery/GhosterySafari#8]
I'm not sure whether this app is actively maintained. Is there a plan to release a universal binary of Ghostery Lite?

**Comment by fcjr** [comment]
Hey @amw thanks for reaching out, just took a look at running Lite on arm and looks like it we don't need to make any changes to get it running! This is definitely something we'd like to do,
![Screen Shot 2021-02-09 at 12 52 00 PM](https://user-images.githubusercontent.com/2053002/107406110-11da5900-6ad6-11eb-95e5-17a1dfc57272.png)

@christophertino looks like we just need to make a new release using xcode > 12, but I'm not sure when we'd be able to ship this.

**Comment by christophertino** [comment]
Fixed in v1.2.0
